# Numpy

In [ ]:
#array==> ndarray
#array supports indexing==> +ve & -ve indexing
# slicing
import numpy
numpy.array(object,dtype=None)

## Creating arrays using numpy

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/srv/conda/envs/notebook/lib/python3.6/site-packages/numpy/__init__.py'>

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
np.array([[1,2],[4,4]])

array([[1, 2],
       [4, 4]])

## np.array(object,dtype)

In [6]:
a = np.array([1,2,3,4,5])
a.dtype

dtype('int64')

In [7]:
a

array([1, 2, 3, 4, 5])

In [8]:
# ExpliciteTypecasting
a = np.array([1,2,3,4,5],dtype='float')
a.dtype

dtype('float64')

In [9]:
a

array([1., 2., 3., 4., 5.])

In [10]:
#i want float32 instead float64
a = np.array([1,2,3,4,5],dtype='float32')
a

array([1., 2., 3., 4., 5.], dtype=float32)

In [11]:
a = np.array([1,2,3,4,5],dtype='float16')
a

array([1., 2., 3., 4., 5.], dtype=float16)

In [14]:
a = np.array([1,2,3,4,5],dtype='bool')
a

array([ True,  True,  True,  True,  True])

In [15]:
np.array(['','','',''],dtype='bool')

array([False, False, False, False])

In [17]:
np.array([None, None, None],dtype='bool')

array([False, False, False])

In [ ]:
#different way
np.array()
np.arange()
np.eye()
np.ones()
np.zeros()

### np.linspace

In [18]:
"""
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
"""
np.linspace(2,20)

array([ 2.        ,  2.36734694,  2.73469388,  3.10204082,  3.46938776,
        3.83673469,  4.20408163,  4.57142857,  4.93877551,  5.30612245,
        5.67346939,  6.04081633,  6.40816327,  6.7755102 ,  7.14285714,
        7.51020408,  7.87755102,  8.24489796,  8.6122449 ,  8.97959184,
        9.34693878,  9.71428571, 10.08163265, 10.44897959, 10.81632653,
       11.18367347, 11.55102041, 11.91836735, 12.28571429, 12.65306122,
       13.02040816, 13.3877551 , 13.75510204, 14.12244898, 14.48979592,
       14.85714286, 15.2244898 , 15.59183673, 15.95918367, 16.32653061,
       16.69387755, 17.06122449, 17.42857143, 17.79591837, 18.16326531,
       18.53061224, 18.89795918, 19.26530612, 19.63265306, 20.        ])

In [19]:
np.linspace(2,6,num=10)

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [21]:
np.linspace(-6,6,8)

array([-6.        , -4.28571429, -2.57142857, -0.85714286,  0.85714286,
        2.57142857,  4.28571429,  6.        ])

In [22]:
# -6 -5 -4 -3 -2 -1 0 1 2 3 4 5 6
np.linspace(-6,6,13)

array([-6., -5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.])

In [23]:
np.linspace(2,6,num=10,retstep=True)

(array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
        4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ]),
 0.4444444444444444)

In [24]:
np.linspace(-6,6,num=13,retstep=True)

(array([-6., -5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.]), 1.0)

In [30]:
np.linspace(1,6,num=13,retstep=True)

(array([1.        , 1.41666667, 1.83333333, 2.25      , 2.66666667,
        3.08333333, 3.5       , 3.91666667, 4.33333333, 4.75      ,
        5.16666667, 5.58333333, 6.        ]),
 0.4166666666666667)

## np.full()

In [31]:
#Return a new array of given shape and type, filled with `fill_value`
#np.full(shape, fill_value, dtype=None, order='C')
#shape=()
np.full((4,4),100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [40]:
np.full((4,4),100,dtype=np.float32)#f8 f==float32
#dtype: 'float','f8',np.float32

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]], dtype=float32)

## random()

In [49]:
#Random values in a given shape.
np.random.rand(5)

array([0.26916226, 0.09613503, 0.46082297, 0.65792443, 0.6088272 ])

In [54]:
d = np.random.rand(3,3)
d

array([[0.30674495, 0.81434079, 0.82301754],
       [0.254572  , 0.54818121, 0.45156643],
       [0.51938376, 0.24454807, 0.63206364]])

In [55]:
d.dtype

dtype('float64')

In [56]:
d.size

9

In [57]:
d.shape

(3, 3)

In [58]:
d.ndim

2

In [112]:
x = np.random.rand(4,4)
x

array([[0.2541294 , 0.00162389, 0.82512577, 0.59375738],
       [0.18182707, 0.25084093, 0.89931893, 0.33696848],
       [0.69713452, 0.33613849, 0.30744414, 0.9590977 ],
       [0.70847626, 0.10585353, 0.34489447, 0.21680159]])

In [64]:
x*100

array([[49.19867136, 89.70897858, 53.78494973],
       [97.63512862, 20.44687297,  0.89255996],
       [36.0370696 , 29.62363299, 92.20502635]])

In [66]:
#randint(low, high=None, size=None, dtype=int)

#Return random integers from `low` (inclusive) to `high` (exclusive).
np.random.randint(3,size=12)

array([2, 1, 1, 2, 2, 1, 1, 0, 1, 0, 0, 1])

In [77]:
np.random.randint(2,12,size=20,dtype='int8')

array([ 7, 10, 11,  8, 11, 11,  7,  6,  9,  3,  7,  3,  9,  9,  8,  5,  3,
       10,  5,  8], dtype=int8)

In [110]:
a = np.random.randint(2,6,10,dtype='int')
a

array([5, 5, 2, 4, 3, 4, 3, 3, 4, 3])

In [107]:
a.dtype

dtype('int64')

In [111]:
#age = 18-35
np.random.randint(18,36,50)

array([28, 29, 33, 34, 30, 23, 30, 22, 21, 25, 33, 34, 31, 27, 25, 34, 27,
       29, 26, 26, 29, 28, 33, 23, 29, 33, 24, 20, 34, 21, 31, 18, 30, 25,
       25, 21, 28, 22, 20, 29, 22, 32, 33, 34, 19, 19, 28, 31, 30, 21])

In [113]:
a

array([5, 5, 2, 4, 3, 4, 3, 3, 4, 3])

In [115]:
x

array([[0.2541294 , 0.00162389, 0.82512577, 0.59375738],
       [0.18182707, 0.25084093, 0.89931893, 0.33696848],
       [0.69713452, 0.33613849, 0.30744414, 0.9590977 ],
       [0.70847626, 0.10585353, 0.34489447, 0.21680159]])

In [116]:
id(x)

139972855061520

In [117]:
# create array y same as that of x
y = x

In [118]:
y

array([[0.2541294 , 0.00162389, 0.82512577, 0.59375738],
       [0.18182707, 0.25084093, 0.89931893, 0.33696848],
       [0.69713452, 0.33613849, 0.30744414, 0.9590977 ],
       [0.70847626, 0.10585353, 0.34489447, 0.21680159]])

In [119]:
id(y)

139972855061520

In [120]:
z = np.copy(x)
z

array([[0.2541294 , 0.00162389, 0.82512577, 0.59375738],
       [0.18182707, 0.25084093, 0.89931893, 0.33696848],
       [0.69713452, 0.33613849, 0.30744414, 0.9590977 ],
       [0.70847626, 0.10585353, 0.34489447, 0.21680159]])

In [121]:
id(z)

139972862438656

In [ ]:
# I want to create 4x4 array which will contain all True values
# I want to create array which will contain all False values
# I want to create 5x5 array in which Diagonal values should be True & non diagonal values should be False



In [122]:
np.random.rand(5,5)

array([[0.17158805, 0.41875782, 0.42234268, 0.42890302, 0.47854859],
       [0.9593969 , 0.89777126, 0.8901265 , 0.19435781, 0.20614254],
       [0.25964303, 0.70550337, 0.02068194, 0.50357517, 0.67178574],
       [0.96493455, 0.42179751, 0.48859186, 0.94742975, 0.96809878],
       [0.736717  , 0.22536834, 0.54067636, 0.05031342, 0.20294178]])

In [ ]:
np.