In [10]:
data is a main important component of data science
data is an input for performing data science

Definition: 
    Bringing insights from data is nothing but data science
    data ===> information
    
Types of data:
    int
    float
    bool
    str==> object
    
    Continueous data
    Discrete data
    Categorical data
        1. Nominal data: where sequence doesnt matter 
            Example: Male,Female
        2. Ordinal data: sequence matters
            Example: High Medium Low
        
    Relationships of data
    

SyntaxError: invalid syntax (Temp/ipykernel_1292/502282786.py, line 1)

In [ ]:
Data:=
    1. structured data: relational, row X columns, Eg. excel, csv
    2. Unstructured data: multimedia data, eg. image, audio,video

Machine Learning
Deep learning
100=50-60(Py+ds)+25(ML)+20(Deployement)

In [ ]:
Data science libraries:
    1. Numpy: numerical python/used for statistical analysis==> array
    2. Pandas: Data analysis==> 
        1. Series 2. DataFrame
    3. Matplotlib: Data visualization
    4. Seaborn: Data visualization
        
        

# Numpy

In [1]:
import numpy  as np

In [ ]:
numpy

In [4]:
a= np.array(100)
a
type(a)

numpy.ndarray

In [ ]:
# Main important thing about numpy is:to create an array
help(numpy.array)

In [ ]:
numpy.array([10,20,30])

In [11]:
numpy.array((10,20,30))

NameError: name 'numpy' is not defined

In [ ]:
numpy.array({1,2,3,4,1,2})

In [ ]:
import numpy as np

### 1 dim array

In [5]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
a.ndim

1

In [8]:
a.size

3

In [9]:
len(a)

3

In [10]:
a.shape

(3,)

In [11]:
a.dtype

dtype('int32')

In [12]:
type(a)
#interview que: what is type of numpy array?

numpy.ndarray

In [13]:
type(np.array([1,2,3.,'A']))

numpy.ndarray

## 2 dim array

In [ ]:
b = np.array([[1.,2.],[3.,4.]])
b

In [ ]:
b.ndim

In [ ]:
b.size

In [ ]:
b.shape#(row,column)

In [ ]:
b.dtype

### 3 dim

In [14]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,1,1],[2,2,2],[3,3,3]]])
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]]])

In [15]:
c.ndim

3

In [16]:
c.shape#(block,row,column)

(2, 3, 3)

In [17]:
# how to convert array to list
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]]])

In [18]:
c.tolist()

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 1, 1], [2, 2, 2], [3, 3, 3]]]

In [19]:
np.info(np.dtype)

 dtype()

Initialize self.  See help(type(self)) for accurate signature.


Methods:

  newbyteorder  --  newbyteorder(new_order='S', /)


In [ ]:
64bit==>8bytes

## Creating arrays using default functions of numpy

In [20]:
# i want to create array with all Zero's
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.zeros((3,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [23]:
#create array with all one's==>1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [26]:
# want identity matrix/array
# whose diagonal elements are 1
np.eye(5)#returns 2 dim array 5 X 5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
#np.info(np.eye)
#help(np.eye)
np.eye?

In [28]:
np.arange(6)#==> equivalent to range

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.arange(2,21)#end is exclusive

In [ ]:
np.arange(1,101,2)#start,stop, step same as that of range in python

In [29]:
np.arange(11,0,-1)

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [30]:
np.arange(1,12)[::-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])