In [1]:
import numpy as np

# How to reshape/manipulate arrays

In [2]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
a.shape

(20,)

In [ ]:
# 2D==> (4,5),(5,4),(20,1),(1,20),(2,10),(10,2)

In [5]:
a.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
a.reshape(10,3)

ValueError: cannot reshape array of size 20 into shape (10,3)

In [8]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# 3D: (2,5,2),(1,10,2),(5,2,2)

In [9]:
a.reshape(2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [ ]:
#reshape is used to conver 1D = nD

In [4]:
b = np.array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [5]:
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [13]:
b.shape

(2, 5, 2)

In [12]:
b.reshape(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
b[0]

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [19]:
b[0].reshape(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
b[0][0:-1]

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [4]:
b[0][::4]

array([[0, 1],
       [8, 9]])

In [6]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
#4 rows and i dont know abt columns
a.reshape(4,-1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [8]:
a.reshape(2,2,-1)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [9]:
a.reshape(-1,-1)

ValueError: can only specify one unknown dimension

In [10]:
b.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## Convert from nDim to 1 Dim always?

In [11]:
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [13]:
#Return a flattened array.
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
#Return a copy of the array collapsed into one dimension.
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
#difference between ravel & flatten?

## How to inplace the reshape changes?

In [16]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
a.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [18]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
#Change shape and size of array in-place.
a.resize(2,10)

In [20]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [21]:
a.resize(4,5)

In [22]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
a.shape

(4, 5)

In [24]:
#shape is also used for in place changes in shape
a.shape = (20)

In [25]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
a.shape = (5,4)

In [27]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [28]:
#transpose array
#rows converted to column
a.T

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [ ]:
(4,5)==> (5,4)

In [30]:
np.transpose(a)

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

# Adding /Removing elements from array

In [4]:
a=np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [5]:
a[0]

array([0, 1, 2, 3])

In [6]:
a[4]

array([16, 17, 18, 19])

In [10]:
a[5]=np.array([10,20,30,40,50])

IndexError: index 5 is out of bounds for axis 0 with size 5

In [11]:
#Append values to the end of an array.
np.append(a,[10,20,30,40,50])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 10, 20, 30, 40, 50])

In [10]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
np.append(a,[[10],[20],[30],[40],[50]],axis=1)

array([[ 0,  1,  2,  3, 10],
       [ 4,  5,  6,  7, 20],
       [ 8,  9, 10, 11, 30],
       [12, 13, 14, 15, 40],
       [16, 17, 18, 19, 50]])

In [22]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [23]:
np.append(a,[[10,20,30,40]],axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [10, 20, 30, 40]])

In [24]:
a[0]

array([0, 1, 2, 3])

In [26]:
np.append(a,[10,20,30,4,5,6,7])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 10, 20, 30,  4,  5,  6,  7])

## if i want to add the values in between

In [27]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [28]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
#Insert values along the given axis before the given indices.
np.insert(a,3,400)

array([  0,   1,   2, 400,   3,   4,   5,   6,   7,   8,   9,  10,  11,
        12,  13,  14,  15,  16,  17,  18,  19])

In [30]:
np.insert(a,20,900)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 900])

In [31]:
np.insert(a,19,900)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18, 900,  19])

In [32]:
np.insert(a,-1,900)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18, 900,  19])

In [41]:
np.insert(a,6,1000)

array([   0,    1,    2,    3,    4,    5, 1000,    6,    7,    8,    9,
         10,   11,   12,   13,   14,   15,   16,   17,   18,   19])

In [ ]:
#Assignment: Insert the values in between according to axis

## Delete: rows and columns

In [33]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [34]:
#Return a new array with sub-arrays along an axis deleted.
np.delete(a,2)

array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [36]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
np.delete(a,np.s_[:5])

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
np.delete(a,[1,6,19])

array([ 0,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [ ]:
#Assignment: Delete the rows and columns in between according to axis

In [42]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [43]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [45]:
n = np.array([20,34,2,4,51,90,56]
            )
n

array([20, 34,  2,  4, 51, 90, 56])

In [46]:
np.delete(n,2)

array([20, 34,  4, 51, 90, 56])

In [48]:
np.delete(n,4)

array([20, 34,  2,  4, 90, 56])

In [49]:
n

array([20, 34,  2,  4, 51, 90, 56])

In [50]:
#remove multiple elements
np.delete(n,[0,4,-1])

array([34,  2,  4, 90])

In [52]:
n

array([20, 34,  2,  4, 51, 90, 56])

In [54]:
n[:4]

array([20, 34,  2,  4])

In [56]:
np.delete(n,np.s_[:4])

array([51, 90, 56])

In [57]:
np.delete(n,np.s_[::2])

array([34,  4, 90])